### ISSUE TITLE
Redirect problem with route and existing folder with the same name

### ISSUE THREAD

**Issue by christianmalek** [bcosca/fatfree#1015]
Hi,

I have a route `GET /services` and a folder `services`. The folder's content shouldn't be shown if the url will be `http://foobar.com/services`. Instead it should redirect the request to the `index.php` file.

The file structure is like this:
```
/index.php
/.htaccess
/services/irrelevant_files
```

And the .htaccess looks like this:
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-l
RewriteRule .* index.php [L]
```

I've registered the `GET /services` route with F3. But if I try to access the URL I get `too many redirects`. Other routes whose names don't collide with existing folders can be accessed unproblematically.
If I just print some debug message in ìndex.php` it's also working. It seems like F3 has some problems in this case.

Maybe someone has an idea about this redirect error.

**Comment by ikkez** [comment]
I guess the rediction-loop happens because the webserver sees that it's an existing folder and appends a `/` to route, that lead to `/services/` in the address, but F3 removes that again a does a redirect to `/services`. 
I think this will always cause trouble and it's maybe better to treat application folders as reserved words for routes. I don't know how, but if you want to fix this nevertheless, it would probably fit best to fix this in your htaccess or refactor your folder structure. Otherwise you need to fix it again when you consider to change the webserver (nginx,etc.)

**Comment by sn0opy** [comment]
Is there a seperate Index file in your `/services`-folder which redirects back to `/` or anywhere else? You could probably fix this issue by removing `RewriteCond %{REQUEST_FILENAME} !-d`. 

This prevent Apache to respect existing folders and will just ignore it.

Keep in mind: this could cause to other problems, like asset folders which aren't handled as normal folders anymore. as @ikkez already recommended, you should rename the folders, if you want to use the same name for a route.

**Comment by christianmalek** [comment]
@ikkez: For the sake of simplicity I'll just fix the name collision and rename the folder.

@sn0opy: There's only the `index.php` file in the root directory and I already removed the `RewriteCond %{REQUEST_FILENAME} !-d` directive.

Thanks, guys!
