### ISSUE TITLE
Route locked

### ISSUE THREAD

**Issue by gmzu** [bcosca/fatfree#1019]
if I use the sleep(15) function in a function class called by the route, all other web routes remain locked until the first route terminates execution.
eg:

config.ini
GET /=CMS->home
GET /login=User->show_login

```
Class User {
    function show_login() {   
        sleep(15);
        ......
  }
}

Class CMS {
   function home() {
     echo "hello";
   }
}

```
if I try to reach "/login" address, the home page route "/" opened in another panel of the same browser does not respond until the execution of sleep(15) ends. 
it's normal?

**Comment by ikkez** [comment]
It is not "normal", but probably a web server configuration issue. Usually the webserver spawns multiple php threads for such things. What web server environment are you using? Maybe our google board would be a better place for this issue.

**Comment by gmzu** [comment]
It is not a web server problem. If I do not use the framework I don't have the issue

**Comment by gmzu** [comment]
investigating further I identified the problem in this line
``
$userid=$f3->get('SESSION.userid');
``
in beforeroute function of master controller class.
The problem seems to be related to some locking mechanism of the session file operated by the framework
if I use
``
$userid=$_SESSION['userid'];
``
the problem disappears

**Comment by ikkez** [comment]
Do you use the database/cache session handler, or the php default one?

**Comment by gmzu** [comment]
I use the php default session handler. With database session handler the problem disappears

**Comment by xfra35** [comment]
That lock is part of the PHP session mechanism. The reason why you didn't experience it with a single `$userid=$_SESSION['userid']` is because you didn't call [session_start](http://php.net/manual/en/function.session-start.php) whereas `$userid=$f3->get('SESSION.userid')` automatically did it for you.

The only way to release the session lock is to call [session_write_close](http://php.net/manual/en/function.session-write-close.php). Calling it just before `sleep(15)` should fix your issue.

**Comment by gmzu** [comment]
thank you very much for your availability and cooperation
