### ISSUE TITLE
template identation and highlight syntax

### ISSUE THREAD

**Issue by albjeremias** [bcosca/fatfree#1047]
I use phpcs for identation and formatting my files.. is there a standard or something for the templates?
I use atom.io to edit my files ... I use this plugin to fix php: https://atom.io/packages/php-cs-fixer

**Comment by ikkez** [comment]
There's no official code style for F3, but I created [this one](https://gist.github.com/ikkez/67ba1363e6645ee16497) for PhpStorm, that matches the dense code blocks of the core pretty much. Write your templates as you like. Some IDEs highlights namespaced html tags, so if you want highlighting in your markup, 
try to write `<F3:check if="{{@foo}}">` instead of `<check if="{{@foo}}">`.
