### ISSUE TITLE
SMTP Class doesn't support text + html message

### ISSUE THREAD

**Issue by dexwerx** [bcosca/fatfree#1051]
the SMTP class can only send a text email or html email, not a single email with both?
This would be a broken up as a multipart message.
https://kevinjmcmahon.net/articles/22/html-and-plain-text-multipart-email-/

seems like a simple enhancement, but using PHPMailer in the meantime.
Thanks!

**Comment by ikkez** [comment]
Actually it can send a multiplart text + html mail, the class is a little bit bare-bone at this point though. You basically need to prepare your mail body with the multipart like this:

```php
$text = 'Hello world.';
$html = 'Hello <b>world</b>';

$smtp = new \SMTP();
$smtp->set('From', 'info@domain.com');
$smtp->set('To', 'info@domain.com');
$smtp->set('Content-Type', 'multipart/alternative; boundary="'.$hash.'"');
$smtp->set('Subject', 'Multipart test');

$hash=uniqid(NULL,TRUE);
$eol="\r\n";
$body  = '--'.$hash.$eol;
$body .= 'Content-Type: text/plain; charset='.$this->charset.$eol;
$body .= $text.$eol.$eol;
$body .= '--'.$hash.$eol;
$body .= 'Content-Type: text/html; charset='.$this->charset.$eol.$eol;
$body .= $html.$eol;

$smtp->send($body,true);
```
I also had hard times to remember the exact construct everytime when I need this, so for little more convenience I put it into a little [mailer plugin](https://github.com/ikkez/f3-mailer)

**Comment by drbraden** [comment]
In the example above, you'd want to initialize the `$hash` variable prior to its usage on line 7.

**Comment by dexwerx** [comment]
@drbraden If you do use the above posted code - note that it is not compatible with attachments etc, because the SMTP->send() generates its own internal $hash / boundary marker.

**Comment by maietta** [comment]
As someone who consistently follows RFC recommendations, I want to point out this nugget on the subject as I believe Fat Free Framework seems to stick well to standards outlines in various RFC standards:

RFC 5322 (https://tools.ietf.org/html/rfc5322) says:

2.1.1.  Line Length Limits

   There are two limits that this specification places on the number of
   characters in a line.  Each line of characters MUST be no more than
   998 characters, **and SHOULD be no more than 78 characters, excluding
   the CRLF**.

   The 998 character limit is due to limitations in many implementations
   that send, receive, or store IMF messages which simply cannot handle
   more than 998 characters on a line.  Receiving implementations would
   do well to handle an arbitrarily large number of characters in a line
   for robustness sake.  However, there are so many implementations that
   (in compliance with the transport requirements of [RFC5321]) do not
   accept messages containing more than 1000 characters including the CR
   and LF per line, it is important for implementations not to create
   such messages.

   The **more conservative 78 character recommendation is to accommodate
   the many implementations of user interfaces that display these
   messages which may truncate, or disastrously wrap, the display of
   more than 78 characters per line, in spite of the fact that such
   implementations are non-conformant to the intent of this
   specification** (and that of [RFC5321] if they actually cause
   information to be lost).  Again, even though this limitation is put
   on messages, it is incumbent upon implementations that display
   messages to handle an arbitrarily large number of characters in a
   line (certainly at least up to the 998 character limit) for the sake
   of robustness.

**Comment by pauljherring** [comment]
Forgot I'd submitted that comment. I think I found the solution to my problem; it's what I'm using at the moment anyway:

```php
	/** @brief Set the body - main call
	*	@param string $plain
	*		(Optional) plain text version of the body
	*	@param string $html
	*		(Optional) HTML version of the body
	*	
	*	Normally, if both are passed, the plain text version should be a simplified
	*	version (and basic equivilent) of the HTML version.
	*
	*	While it's possible to have just the HTML version without the plain text version
	*	this is not recommended.
	*/
	function multipartBody($plain = null, $html = null){
		// https://stackoverflow.com/a/46465392
		// https://gist.github.com/tylermakin/d820f65eb3c9dd98d58721c7fb1939a8
		$hash = false;
		$eol = "\r\n";
		$body = '';
		if (isset($plain) && isset($html)){
			$hash=uniqid(NULL,TRUE);
			$this->header('Content-Type', 'multipart/alternative; boundary="'.$hash.'"');
			$body = '--'.$hash.$eol;
			$body .= 'Content-Type: text/plain; charset=utf-8; format=flowed; delsp=yes'.$eol;
			$body .= 'Content-Transfer-Encoding: quoted-printable'.$eol;
			$body .= $eol; // blank line to separate header from body
			$body .= quoted_printable_encode($plain).$eol.$eol;
			$body .= '--'.$hash.$eol;
			$body .= 'Content-Type: text/html'.$eol;
			$body .= 'Content-Transfer-Encoding: quoted-printable'.$eol;
			$body .= $eol; // blank line to separate header from body
			$body .= quoted_printable_encode($html).$eol;
			$body .= '--'.$hash.'--'.$eol;
		} elseif (isset($plain)){
			$this->header('Content-Type', 'text/plain');
			$body = $plain.$eol.$eol;
		} elseif (isset($html)){
			$this->header('Content-Type', 'text/html');
			$body = $html.$eol;
		}
		$this->body($body);
	}
```

Given the previous comment, I may have to do something about the non-multipart bits...

**Comment by Jiab77** [comment]
@ikkez Are you considering that it's better to use your mailer plugin instead ?

**Comment by ikkez** [comment]
Well that's up to you. It's just an option in case you dont want to / dont have yet implemented a multipart message yourself. However, I've closed this issue, because regarding to the title, the SMTP class is able to send text + html messages. 
(I for myself mostly only send plain text or html.. not both.. so simple SMTP plugin is also fine.. the mailer plugin has some more features though)

**Comment by Jiab77** [comment]
> Well that's up to you. It's just an option in case you dont want to / dont have yet implemented a multipart message yourself.

It's my case actually so I may use your plugin to save development times. It's the main reason I've choses F3 framework because it's light and handle many low levels tasks.

The multipart feature is often used for company mailing process so they can be sure their mail would be read no matter what the mail client support, by adding the text part with the html one, you make sure the text would be read in case the html support is disabled.

Thanks a lot for your reply :+1:
