### ISSUE TITLE
$f3->set('COOKIE.some', true); delete existing cookie and not set new one

### ISSUE THREAD

**Issue by m0x3** [bcosca/fatfree#1070]
Hi!
When i want to set cookie and if it already exists, cookie deletes and nothing more.

I'm commented out this code in /lib/base.php line 340 and all works good now.
`
if (isset($_COOKIE[$parts[1]])) {
	$jar['expire']=strtotime('-1 year');
	call_user_func_array('setcookie',
		array_merge([$parts[1],NULL],$jar));
}
`

I'm look in docs, but not find anything about it and in google too. Please explain what is it, maybe i'm not right to comment out this code and need to do something else?

But it appears only if cookie set without TTL value, first it puts with expires="Session" and on next set it deletes.

**Comment by JohanManders** [comment]
I had the same issue. If the default ttl of 0 is used, the cookie will switch between 'set' and 'unset' every browser refresh. This is because on line 341, the `$jar['expire']` variable gets set to '-1 year', but does not get set back to 0 later on.

I see no point in 'unsetting' the cookie here by setting the `$jar['expire']` variable to '-1 year', so I would propose to remove lines 340 - 344 from /lib/base.php and the problem is gone.

```php5
if (isset($_COOKIE[$parts[1]])) {
	$jar['expire']=strtotime('-1 year');
	call_user_func_array('setcookie',
		array_merge([$parts[1],NULL],$jar));
}
```

**Comment by sand123** [comment]
Have same troubles with cookie set/get

**Comment by ikkez** [comment]
please check the latest release and re-open if the problem persists ;)
