### ISSUE TITLE
Session cookie value is vulnerable to directory traversing / path traversal attack

### ISSUE THREAD

**Issue by ladislavmoravek** [bcosca/fatfree#1073]
https://github.com/bcosca/fatfree/blob/0539cd4c0bba2e6e8231dbca64156123725c9184/lib/session.php#L91

using session value similar to this:

    -H 'Cookie: PHPSESSID=../../../index.php'

i was able to write file outside the file cache folder.

However I was not able to find any practical use on my setup. (having the tmp folder outside of the document root, limited write access for www user only to specific folders).

But almost certainly in case www user is able to write somewhere inside the document root attacker may be able to read the session data, at least part of it. This may or may not lead to security issues depending on what is stored in the session.

Quick fix that seems to work, at least with the file cache, is to use lets say md5 to hash the value coming from session cookie which in turns will be used in the filename creation process. This needs to be done on several places in the session class, it would be nice to have one place for it, like having a setter and getter for the cache name/id.

Please let me know if i have missed any already build in functionality that would prevent this kind of behaviour.

Thank you.

**Comment by xfra35** [comment]
Hmm I was about to write that such hack isn't possible because cached values are prefixed with `SEED`, but I could write outside the cache folder using the following key:

```php
echo $f3->SEED;// abcd1234
$cache=Cache::instance();
$cache->set($key='/../../index.php','bar',60);
```

The first `/../` skips `SEED`. Thus the cache entry is saved into `tmp/index.php` file.

We should probably add a check when using the `folder` cache engine.

Anyway I'm surprised that you could write outside the file cache folder with the hack you've described, because PHP is supposed to reject invalid session ids (` valid characters are a-z, A-Z, 0-9 and '-,'`).

Also the `Session` class adds a `.@` suffix, so you would never be able to write into `index.php`.

As a side note, I was surprised to discover that users can define their own session id by renaming their cookie (as you've demonstrated). You need to enable [session.use_strict_mode](http://php.net/manual/en/session.configuration.php#ini.session.use-strict-mode) to prevent this behaviour. I wonder why it's not enabled by default.

**Comment by Rayne** [comment]
I could also reproduce the issue. Too bad that I didn't look for these problems in F3 while writing my [VirtualPath](https://github.com/Rayne/virtual-path) library.

We should either check if the ID contains only trusted characters or, as lazy workaround, use `basename()` to prevent directory traversal attacks.

**Comment by Rayne** [comment]
> This needs to be done on several places in the session class, it would be nice to have one place for it, like having a setter and getter for the cache name/id.

I think it would be also a good idea to define if `/` or `\` are valid `Cache` keys. If they aren't valid ones then the problem could be fixed in the `Cache` class instead by adding `$key = basename($key)` after the the following method signatures:

* [`Cache->exists()`](https://github.com/bcosca/fatfree-core/blob/93c91537c13c436c972d6679a464b776aca4a96c/base.php#L2405)

* [`Cache->set()`](https://github.com/bcosca/fatfree-core/blob/93c91537c13c436c972d6679a464b776aca4a96c/base.php#L2452)

* [`Cache->clear()`](https://github.com/bcosca/fatfree-core/blob/93c91537c13c436c972d6679a464b776aca4a96c/base.php#L2496)

It wouldn't be necessary to patch [`Cache->get()`](https://github.com/bcosca/fatfree-core/blob/93c91537c13c436c972d6679a464b776aca4a96c/base.php#L2487)
 as it only forwards the possibly malicious keys to a (then safe) method.

**Comment by xfra35** [comment]
Which issue could you reproduce? The one described by @ladislavmoravek? or the one I described?

I expect PHP to ensure that session ids contain only trusted characters, so I don't understand how to reproduce @ladislavmoravek's issue.

**Comment by Rayne** [comment]
> Which issue could you reproduce?

The following code allowed me to reproduce the issue described by @ladislavmoravek with PHP's built-in *development* web-server.

**index.php**

```php
<?php

$f3 = require __DIR__ . '/../base.php';
$f3->CACHE = 'folder=' . __DIR__ . '/CACHE/';

new Session;

$f3->set('SESSION.hello', 'world');
```

**Create Sessions as HTTP Client**

```bash
curl -H 'Cookie: PHPSESSID=ABCDEF' 127.0.0.1:9000
curl -H 'Cookie: PHPSESSID=/../../session-jailbreak' 127.0.0.1:9000
```

**Resulting Directory Structure**

```
.
├── CACHE
│   └── j6wc2ffcgezd.ABCDEF.@
├── index.php
└── session-jailbreak.@
```

**Comment by xfra35** [comment]
Strange... the same test returns a 500 error on my side:
`>session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,'`

I'm on PHP 5.6. Could it be that PHP 7 is more permissive on this matter?

Anyway the `Cache` class needs to be strengthened.

**Comment by Rayne** [comment]
I was able to reproduce the issue with `PHP 7.0.22-0ubuntu0.17.04.1`, the default PHP configuration of (X)Ubuntu 17.04 and `fatfree-core` `93c91537c13c436c972d6679a464b776aca4a96c`.

**Comment by xfra35** [comment]
Done in https://github.com/bcosca/fatfree-core/commit/80303cde24ac4b5f4cdb7289c91b103080135237.

I thought there would need to fix `clear()` and `reset()` as well but after investigating, it appears that `unlink` rejects traversal attempts on non-existing paths (such as `tmp/cache/SEED/../` where `SEED` is not a folder). Only `file_put_contents` allows it, which explain why we need to fix `set()`.
