### ISSUE TITLE
`insert()` does not insert records when table only consists of a primary key

### ISSUE THREAD

**Issue by chaosflaws** [bcosca/fatfree#1090]
I agree this is a rather pathological case, but it has its uses.

Create a table that has only a primary key:

```
CREATE TABLE Test
(
  id   INT AUTO_INCREMENT
    PRIMARY KEY
)
```

And try to insert something:

```
<?php

$f3 = require('f3/base.php');

$f3->set('DEBUG', 3);

$f3->set('DB', new DB\SQL($dsn, $user, $pw));


$mapper = new \DB\SQL\Mapper(\Base::instance()->get('DB'), 'Test');

$mapper->reset();
$mapper->insert();
```

Now,

```
if ($mapper->dry()) {
    print "empty!";
}
```

will return "empty!".

This can be worked around by setting `id` to a nonexisting id, which is by no means optimal. Right now, I am using `exec()`.

I need a table with only a primary key because I have two other tables that use the id as reference.

**Comment by geniuswebtools** [comment]
I would expect this behavior because you've not defined any fields for the mapper to insert.

In this case I would extend the mapper class for this table, so calling insert() does what you want, or just add the property before the insert.

$mapper->reset();
$mapper->id = 0;
$mapper->insert();

MySQL will set the value of `id` to the next auto increment value

**Comment by ikkez** [comment]
The mapper only inserts/updates when at least one of the fields has been changed. Since you probably wont do that for the ID field and do not have any other field, it's just skipping that part.
What you can do however is to set a custom `id` (as @geniuswebtools has suggested) and maybe reset that field in case value `0` does not work, i.e. 
```
$mapper->id = 0;
$mapper->id = NULL;
$mapper->insert();
```
I think doing it with this workaround is fine in your case, as trying to patch the core here might add new edge issues 🤔
