### ISSUE TITLE
How to disable "NOTICE: PHP messages" for any 4XX or 5XX errors?

### ISSUE THREAD

**Issue by nailarch** [bcosca/fatfree#1091]
Custom error template:
`$f3->set('ONERROR',function($f3){ echo \Template::instance()->render('error.html'); } );`
error.html:
```
<!doctype html>
<html lang="ru-RU">
<head>
<title>Error 404</title>
<body><h1>Error 404</h1></body>
</html>
```

php7.1-fpm.log overflows with these 404 errors:
```
`...
[07-Feb-2018 04:05:22] WARNING: [pool www] child 29382 said into stderr: "NOTICE: PHP message: HTTP 404 (GET /wp-content/gallery/hd7s/34550506_ss1_540x405.jpg)"
[07-Feb-2018 04:05:22] WARNING: [pool www] child 29382 said into stderr: "NOTICE: PHP message: [index.php:42] Base->run()"
[07-Feb-2018 04:11:27] WARNING: [pool www] child 29434 said into stderr: "NOTICE: PHP message: HTTP 404 (GET /tag-audi)"
[07-Feb-2018 04:11:27] WARNING: [pool www] child 29434 said into stderr: "NOTICE: PHP message: [index.php:35] Base->error()"
[07-Feb-2018 04:11:27] WARNING: [pool www] child 29434 said into stderr: "NOTICE: PHP message: [index.php:42] Base->run()"
[07-Feb-2018 04:36:21] WARNING: [pool www] child 29440 said into stderr: "NOTICE: PHP message: HTTP 404 (GET /wp-content/uploads/Fly-E195.jpg)"
[07-Feb-2018 04:36:21] WARNING: [pool www] child 29440 said into stderr: "NOTICE: PHP message: [index.php:42] Base->run()"
[07-Feb-2018 04:40:14] WARNING: [pool www] child 29491 said into stderr: "NOTICE: PHP message: HTTP 404 (GET /robots.txt)"
[07-Feb-2018 04:40:14] WARNING: [pool www] child 29491 said into stderr: "NOTICE: PHP message: [index.php:35] Base->error()"
...`
```

**Comment by xfra35** [comment]
What's the value of your [error_log](http://php.net/manual/en/errorfunc.configuration.php#ini.error-log) PHP setting?

**Comment by nailarch** [comment]
```
; Log errors to specified file. PHP's default behavior is to leave this value
; empty.
; http://php.net/error-log
; Example:
;error_log = php_errors.log
; Log errors to syslog (Event Log on Windows).
;error_log = syslog
```
I think it doesn't matter.
Because wordpress is running in the same VPS - and there is no 404 error messages(for 404 pages request) logging in php7.1-fpm.log.

**Comment by xfra35** [comment]
The difference between WP and F3 is that F3 logs 404 errors.

Since your `error_log` parameter is not set, errors are sent to stderr, and since `catch_workers_output` is enable, it ends up in `php7.1-fpm.log`.

You'd better define an error log specific to F3. For example:

```php
$f3->LOGS='logs/';
ini_set('error_log',$f3->LOGS.'error.log');
```

**Comment by nailarch** [comment]
Thanks.
Can you add to F3 some feature like:
'LOGERROR' => '0';
)

**Comment by nikolaosinlight** [comment]
In reading this thread I wonder if there is a way to disable 404 error log entries altogether in Prod.

Why?  I have some Drupal sites that are being flipped to F3 that are hit by spambots and they try to access all kinds of crazy URLs (some to try to hack and others that make no sense) and it is really annoying to have to clear logs or that it polluted the error logs and need to sift for the valid errors.  I would rather take the approach that once we go to production that on the 404 page someone can click a link to report the broken link as it should not happen often if at all.

Is this possible with F3?

**Comment by xfra35** [comment]
I agree that we could improve that part. IMHO, in most cases, logging errors others than 5xx is just filling up logging space for nothing.

I see a few solutions:

1. we add a `LOGERROR` boolean variable to determine if errors are logged to file, but that wouldn't help making a distinction between errors that should be logged (5xx in most cases) and others (400, 401, 403, 404, etc.)
2. we add a `LOGERROR` string variable that contains a list of the error codes to be logged (e.g: `500,403` or `5*,401,403`). That would allow to refine the logging mechanism.
3. we modify the `$f3->error()` so that it only logs errors when `ONERROR` is not set or when it returns `FALSE`. This way, developers could totally bypass the default error display/log mechanism and customize it as they wish. Cons: any error occuring in the `ONERROR` handler itself would be very difficult to track as it wouldn't get logged.
4. we just change the `$f3->error()` function so that it only logs 5xx errors
5. we log all errors when `DEBUG>0` and only 5xx when `DEBUG=0`

**Comment by nailarch** [comment]
I will prefer the fastest way  :)
i think 2 version is more better than other. And logging 5xx and 4xx errors must be disabled by default.

**Comment by ikkez** [comment]
I'm not fine with 4th neither 5th option... I think a simple option to skip the `error_log($text);` part would be ok.

**Comment by xfra35** [comment]
Alright let's go for 2nd option then. How would you name the variable? `LOGERROR`, `ERRORLOG`, `ERRORLEVEL`, `LEVEL`, etc.?

Another idea would be to reuse the `DEBUG` variable, since the new parameter is also about debugging.
We could allow `DEBUG` to be an array:
```php
$f3->DEBUG = 0; // Debug level=0, log all errors
$f3->DEBUG = [0, '*']; // idem
$f3->DEBUG = [0, '5*']; // Debug level=0, log only 5xx errors
$f3->DEBUG = [0, '5*|403']; // Debug level=0, log only 5xx and 403 errors
```

This would also work with .ini files:
```ini
DEBUG = 0,5*|403
```

**Comment by ikkez** [comment]
I can imagine that `DEBUG` might be used for other aspects in userland code as well.. you want to let the default be an integer then? Maybe a `LOGERROR` var would be more appropriate 🤔

**Comment by nikolaosinlight** [comment]
I like option #2 and moreover +1 to having the ability to fine tune the logging by allowing the DEBUG variable to specify fine grain codes as xfra35 suggested.  That way one can use DEBUG = 0 for non-prod and something like DEBUG = [0, '5*'] if they don't care for 4XX errors.

This not only would eliminate 404 errors from filling up logs but also 403 errors if one tries to hit protected pages of the application AND best of all setting to 0 would be completely backwards compatible and not change existing functionality today (that some may prefer).

Really elegant solution to the problem and bonus doesn't add more vars to the F3 configuration.

**Comment by ikkez** [comment]
Actually I think this is a webserver issue. Setup a proper log rotation, gzip and cleanup and just log everything as usual. You never know when you might need it.

**Comment by nikolaosinlight** [comment]
That sounds wonderful in theory but in practice it isn't fun to sift through those logs for errors that are meaningful and find 90% of them are because some dumb bot is trying to hit pages that don't exist or some user is trying to manually enter / type links and generating 404's.  Rotating logs more often and having less history depth to scan for serious / true errors is not the solution IMHO.

Also one has to wonder why WP doesn't log 404's if it is so useful.  Perhaps because there isn't a great reason to do so beyond say Dev / Testing were one really focuses on catching and rectifying 404 errors during Dev / Testing.  Then there are the questions of whether 404 errors are even looked at by system admins vs. users reporting issues.  I have never checked my servers.

Having the flexibility and granularity as xfra35's solution suggests provides a robust solution regardless of system admin preferences as they can log or not log as they like and that only makes F3 an even better framework than it already is... which is tough but then I am quite biased... :-)

**Comment by xfra35** [comment]
In my opinion, the PHP error log purpose is to provide debug information each time an error occurs. Simply logging "error 404" or "error 500" doesn't provide more information than what's already available in the server access log. We need the stack trace and the error text, and that usually comes with 5xx errors, not with others.

**Comment by nailarch** [comment]
i prefer at least disable 404 errors.
5xx errors are very very very rare )

**Comment by nikolaosinlight** [comment]
Your kidding right that “5xx errors are very very very rare” unless you consider one page forms or tiny applications those are the errors you are most needing to see the stack of and address and yes often issues only appear in Prod sadly.

As to Xfra35’s comment.  Yes, exactly, 404 errors have no stack trace and are already available in access logs.  Excellent point.  So there is often no benefit to seeing them in error logs.  The nice thing above your idea is that developers and system admins can decide what is best for them.

**Comment by ikkez** [comment]
As long as it's backwards compatible, I'm fine with an adjustment.

**Comment by xfra35** [comment]
Here it is: https://github.com/bcosca/fatfree-core/commit/39948ffabca583eb745575edcad1a30e5c2f8559

`LOGGABLE` contains the list of loggable statuses. It can be an array (or a splittable string) or the special `*` wildcard (default). Non-digits are considered as placeholders.

All the lines below are working examples:
```ini
; Log all errors
LOGGABLE = *

; Log only 500 and 403 errors
LOGGABLE = 500,403
LOGGABLE = 500|403

; Log only 5xx and 40x errors
LOGGABLE = 5xx,40x
LOGGABLE = 5xx|40x
LOGGABLE = 5**,40*
```

What do you think?

**Comment by nikolaosinlight** [comment]
Personally, I like it very much.

The only minor change I would suggest is that we offer 1 approach and not 2 for the same thing i.e. if we are going with * alone to represent wildcard then use the * as a wild card char and do not include the x as a wild card card AND if are going to use | as a separator then don't include , as a separator.  I know people like options but a fixed format is less checks and simpler all around in this case as it is purely for logging.  If it was something like routes I'd say go creative with options.

```
; Log all errors (default)
LOGGABLE = *

; Log only 500 and 403 errors
LOGGABLE = 500|403

; Log only 5xx and 40x errors
LOGGABLE = 5**|40*
```
At least that is my opinion and if it is too much to change then the feature as-is is great.

**Comment by ikkez** [comment]
@nikolaosinlight well the implementation via a simple regex pattern gives you the bonus to choose any non numeric char to use as a wildcard and that we can use multiple split-chars is as well just possible because already existing framework featrues were used ;)
thx @xfra35 ... looks solid.
