### ISSUE TITLE
Cached keys can be retrieved from CLI but not through an HTTP request

### ISSUE THREAD

**Issue by KindlyFire** [bcosca/fatfree#1094]
Hello,

I add a key to the cache like this:

```php
$f3->set('koa_data', ["key" => "value"], 3600 * 24 * 365);
```

I do this in a file called cli.php, made to run through the CLI. This creates a file called `1wxcqsrfx0e8w.1wgwbyg9dz8ks.var` inside `tmp/cache/`. Later on, during a web request, I wish to retrieve it like so:

```php
echo '<pre>';
echo var_dump($f3->get('koa_data'));
echo '</pre>';
```

And it outputs `NULL`. Could somebody help me figure out what went wrong ?

Some more info: I run the website on a XAMPP setup, using the included PHP exe to run `cli.php` from the windows `cmd`. The configuration variables set at startup are exactly the same in the two cases. I updated the `lib/` dir from master.

EDIT: Forgot to specify that running `php.exe index.php /myurl` DOES show the key, and not `NULL`.

**Comment by xfra35** [comment]
The cache keys are internally prefixed with the value of the `SEED` variable, which [defaults](https://github.com/bcosca/fatfree-core/blob/59f9971900e2ef192c58ecc5cf7d08d90554cc84/base.php#L2368) to:
```php
$f3->hash($_SERVER['SERVER_NAME'].$f3->BASE)
```

So if the value is cached by a web request and retrieved via the CLI, there are chances that `SEED` has changed. You must somehow persist the `SEED` value:
* either force it to some value, so that it remains identical no matter if the request is coming from HTTP or the CLI
* or define `$_SERVER['SERVER_NAME']` when running in CLI mode so that it reflects the HTTP host name.

This second method won't work if the web app is running in a subfolder though (`BASE` would be set in HTTP mode while being empty in CLI mode).

**Comment by KindlyFire** [comment]
Thank you, you rock !
