### ISSUE TITLE
Cache does not support lifetime anymore

### ISSUE THREAD

**Issue by Glandos** [bcosca/fatfree#1111]
The support for memcached in #997 dropped the support for lifetime (see 
b730342). The document doesn't reflect that, and my application (simpleid) is now broken. Is there any chance it will come back?

**Comment by xfra35** [comment]
Well spotted.

@bcosca what was the rationale behind removing the `$lifetime` parameter in https://github.com/bcosca/fatfree-core/commit/a2e2c1d45fd6366e57b00cd6db24f2389914efce and https://github.com/bcosca/fatfree/commit/b730342e6e4ca82802a7d49b5bba008a7a6d21fd ?

**Comment by ikkez** [comment]
Looks like it's way faster for redis and memcache to simply delete by key, instead of serializing very cache entry and looking into it for its lifetime setting.. with a very big cache, this could be a sensitive point.

**Comment by ikkez** [comment]
Could it be an option to maybe put the expiration time into the cache-key? So we could find that with a regex search? Anyway.. in the form $lifetime was there, it probably wont come back, as it's too expensive to catch-all entries, unpack, read and process cached data just to see if it's within $lifetime or not.. so, closing this now. sry.
ref. fixed in docs: https://github.com/F3Community/F3com-data/commit/f4cb6f25bba84dba94317d1bf7b68a48f1fd328e
