### ISSUE TITLE
Server Error/404 after upgrade to 3.6+

### ISSUE THREAD

**Issue by v2k** [bcosca/fatfree#1112]
Not having much luck whenever I upgrade the framework. (see #1084 for config)  

Only thing I can find in the release notes is regarding the PHP version, which in my case is: PHP 5.4.4-14+deb7u8 (fpm-fcgi); I nuked the framework's tmp files; server doesn't seem to be using any caching.  I'm changing versions via composer.

3.5.1 works.

3.6.0:
Internal Server Error
Fatal error: syntax error, unexpected ';'

3.6.1-*:
Not Found
HTTP 404 (GET //mydomain.com/)

Until
3.6.4:
Internal Server Error
Fatal error: syntax error, unexpected ';'

**Comment by v2k** [comment]
I guess the fix to #1084 isn't in until 3.6.4; so only that error is valid.

**Comment by v2k** [comment]
Not sure this is useful, but here's the php error:

` [error] 24307#0: *231 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ';' in /var/www/mydomain.debug.com/public/tmp/1yocpxhca6800.3pyqmzc8wjs40.php on line 495`

**Comment by v2k** [comment]
This turned into an excersize for myself.  The ';' in the urlencode here was causing the issue; not sure why this became a problem with the framework update.

```
<iframe height=300 width=85% src="https://www.google.com/maps/embed/v1/place?
q={{ urlencode("New York City, USA"); }}
                        &zoom=13
                        &key=mykey">
</iframe>

```

**Comment by ikkez** [comment]
This is because of some fixes we need to introduce for https://github.com/bcosca/fatfree/issues/1048 and https://github.com/bcosca/fatfree-core/issues/205, but there is no example in the docs that say you have to use `;` to close an expression,.. it was never stated that it's allowed or disallowed, but it was not needed at all, so yes we should document this behaviour now, but IMO it's not a bug that it's not working anymore this way.
