### ISSUE TITLE
Bad practice of silencing error

### ISSUE THREAD

**Issue by dmitrywicked** [bcosca/fatfree#1136]
https://github.com/bcosca/fatfree/blob/a841d838e8f146486d85e4947fb92e2fa78fdeb8/lib/base.php#L2045

Hello, isn't there better way to handle error from file_get_contents than silence it with @

could custom error handler be used instead for example to turn this into exception and handle properly?
E.g. 
```
funcCallWithException($funcName, $args = [], $level = E_ERROR)
{
        set_error_handler(function($errno, $errstr){
            throw new \Exception($errstr);
        }, $level);
        $result =  call_user_func_array($funcName, $args);
        restore_error_handler();
        return $result;
}
```
Thank you.

**Comment by pauljherring** [comment]
Also at 
https://github.com/bcosca/fatfree/blob/a841d838e8f146486d85e4947fb92e2fa78fdeb8/lib/web.php#L345

**Comment by Jiab77** [comment]
Errors should be logged somewhere, even in a simple log file...

**Comment by KOTRET** [comment]
possibly it is not always desired to log the error - sometimes you just don't care if the file exists, get the content or just leave it empty, so maybe we need to evaluate the entry points first instead of wrapping in every case.

**Comment by Jiab77** [comment]
sure @KOTRET you right, too much entry validation can decrease performances but for this case when you silent errors on `file_get_contents` you get no idea why it fails (if it does) and if the given URL is malformated or done in a way to bypass server security. In these case we (users) need to know what could be the issue, what was the passed data when it fails, etc... Maybe a simple Generic Exception Class or Method would be enough and if error happens, then just pass the returned data into the Generic Exception class / method. Let me know if I'm not clear... English is not my native language.

**Comment by ikkez** [comment]
Well, `$f3->read` is a simple little method that reads file contents or not. I think that's easy enough for anyone to work with. If you'd like to validate the files accessibility, I'd suggest to use [`is_readable`](http://php.net/manual/en/function.is-readable.php) upfront. You can catch that `E_WARNING` if something's wrong.

**Comment by xfra35** [comment]
We could make `$f3->read` return `FALSE` on errors, just like `$f3->write` does:

```php
function read($file,$lf=FALSE) {
    $out=file_get_contents($file);
    return $lf && $out!==FALSE?preg_replace('/\r\n|\r/',"\n",$out):$out;
}
```

**Comment by Jiab77** [comment]
@ikkez I see you loved my use of `is_readable` in my past code :grin: . Why not just add it to the actual code, that way the method would return false when trying to read the given file, what do you think about that?

**Comment by pauljherring** [comment]
> Why not just add it to the actual code

Presuming best case of the caller knowing the files is going to be there all the time, it's a useless test. It's adding unnecessary bloat.

Presuming the worse case of the caller knowing the file might not be there, then they should check that the file is there beforehand.

Why not simply wrapper the call if your project needs the check all the time?

```php
function my_real_read($file){
    if (is_readable($file)){...
...
}
```

Neither of which addresses what happens if it's a URL of course...

**Comment by Jiab77** [comment]
> Presuming best case of the caller knowing the files is going to be there all the time, it's a useless test. It's adding unnecessary bloat.

You should not presuming that way. When you are working with many different people that have their own permissions sets, sometimes you can loose read access on known files because of this reason. So having the code testing the readability every time is time saving because you can be sure when calling `$f3->read()` the requested file would be readable and you get sure to get it's contents.

**Comment by pauljherring** [comment]
> You should not presuming that way.

My code, my presumption if I want. 

Play `whatiffery` all you wish, but it's easier to add 'bloat' like this when you know you need it on a case by case basis, than remove it when you know you don't.

Otherwise you start getting into situations where you end up doing these tests all the way up and down the stack, and performance takes a hit.

**Comment by Jiab77** [comment]
> My code, my presumption if I want.

Agreed. I was just sharing my point, no need to be mean.

**Comment by ikkez** [comment]
The `read` method is used interally a lot, i.e. for cache or template files that are generated by the framework itself. Where it's necessary, existence check are already placed. Just adding another one here, "just to be sure" would double the IO calls, which indeed might impact performance.
I see no need to change anything here. Lets stop being nitpicking and care about more important issues instead. thanks all.
