### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by archistico** [bcosca/fatfree#1137]
Do you have a complete example of authentication and authorization with f3? Not http, but add user on the database etc.
Thank you

**Comment by pauljherring** [comment]
There won't be, because there's so many ways of doing (bits and pieces of) it. 

I suggest - perhaps - you read up on user management in general for PHP and adapt that to F3. Areas you'll (probably) need to deal with, or at least look into, off the top of my head:
- adding users
- expiring/resetting passwords
- emails for registration/password resets
- storing passwords securely
- preventing hack attempts without inconveniencing legitimate users
- OTP
- Captchas
- cookies
- banning/removing users
- preventing/monitoring sock-puppets
- Avatars
- GDPR
....

**Comment by archistico** [comment]
Thank you, but I move my project to Symfony
Only "storing passwords securely", XSS, "preventing hack ", CRSF etc. is not a simply task 
I think it could be useful for many a starting point
