### ISSUE TITLE
$f3->set(...,$ttl=0) Bypass Caching

### ISSUE THREAD

**Issue by lsafelix75** [bcosca/fatfree#1153]
Hi,

I am trying to save SESSION.id through:
   $f3->set(SESSION.id, 'user' ); #default $ttl=0

But, my SESSION.id never get saved. When i go through the base.php code, i see the following:
 ```
if ($ttl)
			// Persist the key-value pair
			Cache::instance()->set($this->hash($key).'.var',$val,$ttl);
		return $ref;
```
Is this as per degined? I thought $ttl=0 suppose to save the variable infinitely? Thanks

**Comment by ikkez** [comment]
You do not want to save a session value to cache, otherwise every user would get that value from cache, if existing. So forget about the $ttl on SESSION vars. If you want to extend the session time duration, see `JAR.expire` in F3 and `session.gc_maxlifetime` and `session.cookie_lifetime` in your php.ini

**Comment by rmanleyreeve** [comment]
The key should be a string, try: $f3->set('SESSION.id', 'user' );
> set - Bind value to hive key
> mixed set ( **string $key**, mixed $val [, int $ttl = 0 ] )
>
