### ISSUE TITLE
Bug: Using route /app at begining doesn't find anything

### ISSUE THREAD

**Issue by natxocc** [bcosca/fatfree#1236]
Example:

`$f3->('GET /app/first', 'Route->page');` Doesn't work
`$f3->('GET /first/app', 'Route->page');` Does work

Nothing with /app at begining does work

**Comment by fmagrosoto** [comment]
I think what does not exist is the way you are using the route.

`$f3->reroute('/app/first')
`
or

```
$f3->route('GET /app/first, function($f3){
echo 'it works!;
);
```

or 

**[routes]**
`GET /app/first = Route->page`

**Comment by fmagrosoto** [comment]
This is because .htaccess declaration.


RewriteEngine On
**RewriteRule ^(app|dict|ns|tmp)\/|\.ini$ - [R=404]**
RewriteCond %{REQUEST_FILENAME} !-l
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* index.php [L,QSA]
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

Change the directories you want get access.
For example:

**RewriteRule ^(App|dict|ns|tmp)\/|\.ini$ - [R=404]**

Change app for App... and will work!

**Comment by natxocc** [comment]
> This is because .htaccess declaration.
> 
> RewriteEngine On
> **RewriteRule ^(app|dict|ns|tmp)/|.ini$ - [R=404]**
> RewriteCond %{REQUEST_FILENAME} !-l
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule .* index.php [L,QSA]
> RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
> 
> Change the directories you want get access.
> For example:
> 
> **RewriteRule ^(App|dict|ns|tmp)/|.ini$ - [R=404]**
> 
> Change app for App... and will work!

Thanks for this detail! :-)
