### ISSUE TITLE
PHP 8.1 issue

### ISSUE THREAD

**Issue by joanhey** [bcosca/fatfree#1241]
`PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in /fat-free/vendor/bcosca/fatfree-core/base.php on line 2533`

**Comment by pauljherring** [comment]
https://github.com/bcosca/fatfree/blob/master/lib/base.php#L2533
https://github.com/bcosca/fatfree/blob/3.7.3/lib/base.php#L2533 (it's the same here):

```
2533		if (PHP_SAPI=='cli-server' &&
2534			preg_match('/^'.preg_quote($base,'/').'$/',$this->hive['URI']))
2535			$this->reroute('/');
```

**Comment by joanhey** [comment]
It's using v3.7.2 
https://github.com/bcosca/fatfree/blob/3.7.2/lib/base.php#L2533

I'll try now with v3.7.3

**Comment by joanhey** [comment]
With v3.7.3
`PHP message: PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in /fat-free/vendor/bcosca/fatfree-core/base.php on line 2538`
https://github.com/bcosca/fatfree/blob/3.7.3/lib/base.php#L2538

**Comment by joanhey** [comment]
https://wiki.php.net/rfc/restrict_globals_usage

**Comment by Ayesh** [comment]
The relevant snippet is:

```php
if (ini_get('auto_globals_jit'))
			// Override setting
			$GLOBALS+=['_ENV'=>$_ENV,'_REQUEST'=>$_REQUEST];
```

It basically tries to outsmart the lazy population of super globals, and PHP 8.1 does not allow it. See [PHP 8.1: `$GLOBALS` variable restrictions](https://php.watch/versions/8.1/GLOBALS-restrictions).

I don't understand the reason behind this. PHP should seamlessly populate the super globals the first time it is retrieved, and I think it's alright to simply remove the highlighted snippet.

There are few more deprecation notices popping up (`Return type of Base::offsetunset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void,...`, etc.) due to [PHP 8.1: Return types in PHP built-in class methods and deprecation notices](https://php.watch/versions/8.1/internal-method-return-types)

I have one site that uses F3, and I will be making a PR that tries to bring PHP 8.1 compatibility.

**Comment by ThomasROULSON** [comment]
I was just about to point these issues out. I fixed them by reluncantly doing the following modifications to base.php file:

2358:
Replace:
` $GLOBALS+=['_ENV'=>$_ENV,'_REQUEST'=>$_REQUEST];`
           
With:
` $GLOBALS['_ENV'] = $_ENV;
$GLOBALS['_REQUEST'] = $_REQUEST;`

And finally, insert the attribute `#[\ReturnTypeWillChange]` above the following functions:

2237: offsetexists
2247: offsetset
2256: offsetget
2265: offsetunset

These changes fix the issues I've been having as far as I can tell but there could be more.

**Comment by Ayesh** [comment]
To not duplicate the efforts, @slicke has made a PR at bcosca/fatfree-core#332 with what seems to be all of the changes.

**Comment by yura-x** [comment]
> With v3.7.3 `PHP message: PHP Fatal error: $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in /fat-free/vendor/bcosca/fatfree-core/base.php on line 2538` https://github.com/bcosca/fatfree/blob/3.7.3/lib/base.php#L2538

Same error on '3.7.3-Release' version:
PHP Fatal error:  $GLOBALS can only be modified using the $GLOBALS[$name] = $value syntax in lib/base.php on line 2538

**Comment by slicke** [comment]
My changes where merged into this PR, which I think fixes most issues :) https://github.com/bcosca/fatfree-core/pull/333
