### ISSUE TITLE
CORS OPTIONS preflight 404 if not routed

### ISSUE THREAD

**Issue by riccardo2k13** [bcosca/fatfree#1242]
I'm building an API rest app. I was having issues with CORS preflight fail.
I am not using the $f3->map(). I am mapping every routes in a custom routes.ini

Reading the docs I thought I could not care about OPTIONS, but if I do not route the OPTIONS, it always triggers a 404.

![CORS preflight fails](https://user-images.githubusercontent.com/64069592/142857948-029c9edd-b404-494b-b98e-7e42162c8596.jpg)

I must add a [*OPTIONS /api/... = Ctr->preflight*] to handle it, where the preflight method just contains an exit function. Then f3 does the rest of the job

![immagine](https://user-images.githubusercontent.com/64069592/142858089-4397ec53-f898-449f-9868-37a4f73b98f7.png)

**Comment by ikkez** [comment]
In order to make it work, you just have to have a route at /api/v1/login .. i.e. when you have defined a GET or POST route for it, the OPTIONS preflight is collecting the available http methods that are available, returning a `Access-Control-Allow-Methods: OPTION,GET,POST` header. This should work out of the box. 404 means that the router probably has not found a route for the resource the request is trying to access.

**Comment by ikkez** [comment]
Well then it's probably a bug with the ajax flag, which should be ignored in such a case

**Comment by Joseffb** [comment]
I Second to just use the POST /api/v1/login = Api_Auth_Controller->login method. 

I also do this in my middle-ware router (your pre-flight?) to handle any custom headers

```		$this->fw->copy('HEADERS.Origin','CORS.Origin');
		$this->fw->set('CORS.Origin','*');
		$this->fw->set('CORS.headers',['token','content-type', 'x-property-id']);
```

**Comment by riccardo2k13** [comment]
In fact I will remove the [ajax] specification. Thanks to all.

**Comment by ikkez** [comment]
fixed.
