### ISSUE TITLE
Suggestion: add option for turning off redirect for GET /.../?... routes

### ISSUE THREAD

**Issue by powder96** [bcosca/fatfree#395]
Hi. I'm working on an old website and it has to support this API:

```
GET /abc/def/?param=@param
```

The problem is that F3 does not want to pass that request to the application. Instead, it [generates a HTTP redirect](https://github.com/bcosca/fatfree/blob/master/lib/base.php#L1087) to `/abc/def?param=@param`. Unfortunately, this is not what I need it to do because that would break the backward compatibility. It would be nice to have an option for turning off this automatic redirect for a specific route.

**Comment by stephen322** [comment]
Can this be re-opened?  I too would like trailing slash control, ie. respect for how it's listed in route().  Ultimately, the web dev knows whether a route should be a "file" or "directory".
For example, you could have /abc/@data/@subdata/, where /abc/@data/ is indeed a "directory" or pretty-page listing of @subdata.  It makes much more sense to have the trailing slash in this case.
It has practical effects too:
A relative form action="someaction" under /abc/@data/ would correctly point to /abc/@data/someaction, whereas /abc/@data would default point to /abc/someaction even though someaction might be specific to @data.

**Comment by ikkez** [comment]
Your form action issue is usually solved by a simple `<base>` tag in your html document http://www.w3schools.com/tags/tag_base.asp

**Comment by stephen322** [comment]
@ikkez Thanks, that solves my relative path issues.
But still would be nice for an f3 option to observe the trailing slash / control redirects.

**Comment by kavin-90** [comment]
Not necessary `<base>` is good if you use it well 

Failing Example
`<base href="{{@BASE}}"/>` this will return `<base href="/"> ` so that base url is invalid because it not full url.

**Comment by jdv145** [comment]
I'm not a regular github poster so my apologies beforehand if i don't follow common rules. I just wanted to add a comment on this. I got the explicit request from a SEO company (i'm a techie) to use trailing slashes so it is giving me a bit of a headache. 

I understand the comments made, and the chosen default. And if it could be solved with just htaccess it would be fine (sort of). But also the named url's are not correct anymore and its just a problem waiting to happen when the routes.ini have to be made with this in mind.

Wouldn't it make more sense (like it has been mentioned before) to keep the default behavior, but add a parameter to the run function? It seems a bit forceful to automatically redirect without having an option to disable it, although usually it is clearly the best option.

Just my 2cents

**Comment by ikkez** [comment]
So easy to solve: Tell the SEO company that it doesn't make a difference to the SEO ranking for google (it really does not). And if you take the effort to add trailing slashes, it just adds more complexity to it, like handling duplicate content (url with trailing slash and without), redirecting old links, link-generation, etc... and it doesn't even make sense to force a "directory"-looking url to a document-like page. Adding a trailing `.html` or something would be the only reasonable suggestion IMO, but that's something no one want to see these days either. nevertheless, beating your system to archive trailing `/` is probably a disproportionated task, and if the SEO company does not have any benchmarks to this change, I would reject the request for that reason. There were systems out there in the early days, that didn't handled trailing slashes and produced duplicate content URIs, but F3 is not one of those and nowadays google also is clever enough to recognize such so the whole point from the SEO agency is negligible.
just my 2 cents

**Comment by nickedgar** [comment]
I got circular redirection from this and just commented it out. Shame it
wasn't configurable. We have a hybrid mess of several apps that F3 has to
'play nice' with, and other solutions weren't viable.

**Comment by jdv145** [comment]
I dont want to talk so much about my specific situation(since it is not relevant to f3), but i already expressed my opinion on the urls 2 times before this even became an issue. In the end i try to keep all stakeholders satisfied, particularly if they are payed and _responsible_ for areas i'm not an expert on.

That being said, i dont disagree at all that the current implementation is a fine solution in most of the cases. At the same time it still feels sort of weird (at least to me) if a router/mapper does automatic redirecting without having an option to turn this of. Some might rather have a 404 then being auto-magically redirected to the "right" page. For me it seems sensible to make any correcting behavior optional. Adding a parameter like 

`function run($disableRedirection=false) `

also is a reminder to the user of f3 that redirection might happen. I dont disagree at all that f3 does it the right way. I just wanted to mention that htaccess is not a solution in all cases, since that was mentioned above. And i'm definitely not going to shoehorn a solution onto something when its not a natural fit, because that means way more trouble ahead i'm sure.
