### ISSUE TITLE
New feature : set locale automatically

### ISSUE THREAD

**Issue by xfra35** [bcosca/fatfree#522]
Hi,

is it possible to set automatically the locale when setting the `LANGUAGE` variable?

Right now the locale is not set before a call to the `format()` function.

**Comment by dmueller-workmatrix** [comment]
FYI
This led to problems when I was using an external soap api with float data. Adding multilanguage support using f3's `LANGUAGE` changed the '.' floating decimal literal to ',' for some languages.
Now using `number_format()` to prevent this. Felt a bit like unexpected behaviour, maybe because the automatic locale change was not documented.

**Comment by xfra35** [comment]
Ok thanks I've added it in the [docs](http://fatfreeframework.com/quick-reference#language).

If you want to keep the english numeric format, you can force `setlocale` after setting `LANGUAGE`:

```php
$f3->set('LANGUAGE','de-DE');
setlocale(LC_NUMERIC,'en_US.UTF-8');
```

**Comment by dmueller-workmatrix** [comment]
Thanks! I was actually doing this after I posted the comment! :)
(I used a config.ini file to set the language before).
Thanks a lot, f3 ftw! :+1:
