### ISSUE TITLE
Cache cannot cope with circular objects

### ISSUE THREAD

**Issue by ChrisBAshton** [bcosca/fatfree#798]
I have an array of objects: `$disputes`.

These objects use the state pattern: `$this->state = SomeStaticClass::getState($this)`

And in the state object, I hold a reference to the passed instance:
```php
public function __construct($dispute) {
$this->dispute = $dispute;
```

Outside of the F3 framework, this works fine - but if I try storing disputes using set, the application hangs and then dies with a white screen:

`$f3->set('disputes', $disputes);`

If I don't set globally I get a bit more information:

` echo View::instance()->render('layout.html', 'text/html', array('disputes' => $disputes));`

=>

#### Internal Server Error
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes)`

Like I say, outside of F3 this seems to work - I can var_dump or echo the $disputes array to the page. Looks like F3 can't cope with recursive objects. Anyone have any ideas on how to overcome this in an F3-friendly way while still using the state design pattern?

**Comment by KOTRET** [comment]
guess this has to do with deep copies for output rendering: for rendering purposes a copy is made, otherwise value-escaping for the view will affect the real values. Consider changing your the data for output output and keep the MVC-Principle in mind.

**Comment by xfra35** [comment]
@ChrisBAshton your issue comes from View escaping mechanism. When `ESCAPE=TRUE`, variables passed to the view are automatically escaped. This can be a memory consuming operation if variables are deeply nested objects.

To avoid this issue, you can either:
* disable `ESCAPE` and manually `|esc` every outputted sensitive variable
* or have your `Dispute` class implement the `IteratorAggregate` interface and define the values that need to be escaped inside the `getiterator()` method. If `Dispute` is a DB Mapper, then it already implements that interface.
* or cast `Dispute` objects to arrays before rendering view. If `Dispute` is a DB Mapper, then the `cast()` method is already there.
