### ISSUE TITLE
beforeerase trigger called, with empty DB\SQL\Mapper.

### ISSUE THREAD

**Issue by dexwerx** [bcosca/fatfree#803]
beforeerase is called after the Mapper fields are blanked, it should be called before all the values are set to NULL.

**Comment by ikkez** [comment]
I think this is no bad idea. Nevertheless, you created a simliar PR already at bcosca/fatfree-core#39
It would have been better to have patches for all mapper in the pull-request. And it would be nice if you can seperate the commits regarding to the issue. i guess "skip calls to 'load' trigger on dry cursor position" is another issue.

**Comment by dexwerx** [comment]
still getting the hang of github. I should have checked the previous issue before posting this one!
Thanks.

**Comment by ikkez** [comment]
I had another look at this. 
Currently, the beforeerase trigger IS called with a hydrated mapper. This change should not be necessary, since the parent call to Cursor->erase will split the query array and does call $this->skip(0); which in fact restores the previous changes. I guess it does not work for you anymore since you modified your Cursor class in https://github.com/bcosca/fatfree/issues/797#issuecomment-77863146
Despite the fact that this is maybe also a weird behaviour, as you would still be able to get the fields from a deleted record, I think this issue here is invalid. Let's continue this on #797
