### ISSUE TITLE
Suggestion: Allow manual override of 'pkey' flag for each field in DB\SQL\Mapper as to enable manipulation of data in views

### ISSUE THREAD

**Issue by jmversteeg** [bcosca/fatfree#805]
As of right now, the `DB\SQL::shema` method will automatically detect the structure of a table or view. This generally works great, except for that it cannot detect the primary key field when using views (which I often tend to use since they provide an excellent layer of abstraction between the mapper and the database) and thus the records will be read-only.

A proposed solution to this would be adding a method to the `DB\SQL\Mapper` class, something along these lines:

```php
/**
 * Determines whether the given field has a primary key index 
 * (and thus should be used to keep track of individual records)
 *
 * @param string $fieldName The name of the field
 * @param array  $field     An associative array containing the field info
 *
 * @return bool
 */
protected function isPkey($fieldName, $field)
{
    return $field['pkey'];
}
```

All checks of `$field['pkey']` should in that case be replaced with `$this->isPkey($key, $field)` where `$key` is the name of the field.

This way the `DB\SQL\Mapper` class can be extended and the `isPkey` method overridden, e.g.

```php

class ViewMapper extends \DB\SQL\Mapper {
    
   protected function isPkey($fieldName, $field)
   {
      return parent::isPkey($fieldName, $field) || in_array($fieldName, ['id'])
   }

}
```

This is something I have implemented as a fork of fatfree (even though that particular fork is probably not very suitable as a PR), and I was wondering if it was something that could be considered to be added to the core.

**Comment by bcosca** [comment]
@ikkez: What are your thoughts?

**Comment by ikkez** [comment]
Well, despite the fact that not all views are updateable anyways, I think that having the possibility of updating at least some views, which support it, is nice. Since the schema query on views doesn't tell us about any used pkeys, a solution like the one above would do the trick, yeah. But I could imagine it would fit better into the mapper->schema proxy method from here: https://github.com/bcosca/fatfree-core/blob/master/db/sql/mapper.php#L588
maybe we just add a setter argument here, like this:

```php
function schema($fields=null) {
  if ($fields)
    $this->fields = $fields;
  return $this->fields;
}
```

So it would return the schema as usual, or set the schema if `$fields` is present. In the custom model you can overwrite the pkey settings for views like this:

```php
class ViewMapper extends \DB\SQL\Mapper {
   function __construct() {
      parent::__construct( \Base::instance()->get('DB'), 'table');
      $schema = $this->schema();
      $schema['id']['pkey'] = TRUE;
      $this->schema($schema);
   }
}
```

This way you need to call it just once after initializing and do not need to trigger a method like `isPkey()` all the time.

**Comment by jmversteeg** [comment]
Thanks for your consideration. This seems like a neat implementation, both semantically and performance-wise.
