### ISSUE TITLE
Parsing issue of empty tag like <option></option>

### ISSUE THREAD

**Issue by intermike** [bcosca/fatfree#864]
Greetings.

I have custom function for tag **option** that extends Template:
```PHP
$tmpl->extend('option','\Template\Tags\Option::render');
```
But I've encountered the issue where HTML like
```PHP
<option></option>
<option value="1">1</option>
<option value="2">2</option>
```
was parsed as one node only (the rest of content becomes lost)
```PHP
<option></option>
```
It seems  PHP function **isset($a['key'])** doesn't work properly with array like
```
$a = array('key' => &NULL)
```
Location: template.php => \Template::parse => Find matching start tag
```PHP
if (is_array($item) && isset($item[$match[2]])) {
```
Working properly if replaced with
```PHP
if (is_array($item) && array_key_exists($match[2], $item)) {
```
Thanks.

**Comment by ikkez** [comment]
Thanks for reporting. This should already be fixed in the edge version of the core and will be integrated in the next release. Refs:
https://github.com/bcosca/fatfree-core/pull/77
https://github.com/bcosca/fatfree-core/commit/de01498bc5a475cc71832cb115e5604463f3ee6b#diff-13e5580ca26ea5de947e855a28fb0774R286
https://github.com/bcosca/fatfree-core/blob/master/template.php#L286
