### ISSUE TITLE
 Offline vesion of framework API documentation 

### ISSUE THREAD

**Issue by hmacube** [bcosca/fatfree#905]
there is no lib/api/index.html in the distribution package , where is it?

> The framework API documentation is also contained in the distribution package, at lib/api/index.html 
> - http://fatfreeframework.com/api-reference

**Comment by Rayne** [comment]
You are right, it's missing. You can download a copy of the documentation at [F3com-data](https://github.com/F3Community/F3com-data). If you want the complete website, add [F3com](https://github.com/F3Community/F3com).

**Comment by ikkez** [comment]
We're removed it from the /lib folder because, A. we're not able to get oxygen working ^^ B. the docs itself have nothing to do within the core source, especially they were big and took most time while syncing files with different servers, C. we wanted to put them into the fatfree-dev branch but go lost with A.
And since the auto generated docs do not have anything special then looking at the source directly, we just did not investigate this any further. As @Rayne mentioned, the F3com docs are downloadable and much more detailed.

**Comment by Cairan** [comment]
I just downloaded the framework and spent 2 hours trying to troubleshoot why the /userref route worked but not the /lib/api one... In the name of preventing further undue hairloss in new users of the framework, the welcome.htm content should really, really remove the link reference to the local API doc which is now, as I've just discovered, removed from the distribution, and therefore, really non-existent in the framework content. :)
