### ISSUE TITLE
optional params in route definition

### ISSUE THREAD

**Issue by Phisherman** [bcosca/fatfree#915]
At the moment I use arrays to define optional params on routes like

```php
$f3->route([
    'GET /api/events',
    'GET /api/events/@organisation'
], function (\Base $f3) {
    if ($f3->get('PARAMS.organisation') !== null)
        echo "ALL EVENTS FROM ORG";
    else
        echo 'ALL EVENTS';
});
```

If there are too many optional params the array syntax get's a bit repeating. I suggest to allow some syntax like `GET /api/events/?organisation` for optional params.

**Comment by geniuswebtools** [comment]
I would recommend you use the map() method instead of route.  You can then use classes to define your business logic and make your code more manageable.

$fw->map(array(
    '@apiObject: /api/@object',
    '@apiObjectAction: /app/@object/@action',
    '@apiObjectActionId: /app/@object/@action/@id',
    '@apiObjectActionOpt: /app/@object/@action/@id/@option',
), '@object');


The above code creates a logical flow for your URL patterns, and allows you to manage them in a defined class.  Map by default will look for get(), post(), delete() and put() methods.

Using a class you can define the optional params as members in the contstructor, and use them in each of the 4 public methods.  I then create private methods that are called based on the actions.

/api/events -> Events->get()

/api/events/add -> Events->post() // Creates a new event

/api/events/edit/15 -> Events->get()->edit() // Gets Events->id = 15

/api/events/edit/15 -> Events->put()->edit() // Edits Events->id = 15

/api/events/edit -> Events->{REQUEST_METHOD}()->edit() // Throws an error because Events->id is null

The basic idea is all of this logic can be handled in a class, not a lamda function, which I would agree would by difficult to manage w/ additional params added to the route.

**Comment by emanwebdev** [comment]
@geniuswebtools +1

**Comment by Phisherman** [comment]
@geniuswebtools Thanks!

**Comment by emanwebdev** [comment]
@Phisherman imho worth adding @geniuswebtools 's reply to the F3's official doc, somewhere around http://fatfreeframework.com/base#Routing

**Comment by Phisherman** [comment]
@emanwebdev  Was this an indirect appeal to me?

**Comment by emanwebdev** [comment]
@Phisherman no, direct :100:
