### ISSUE TITLE
Template afterrender is not saving $data

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#922]
Hello,

I have this code for afterrender the returned $data is not saved in the cached template:

```php
\Template::instance()->afterrender(function ($data) {
            foreach (Assets::instance()->getGroups() as $group) {

                if (preg_match('<!--\s*assets-' . $group . '+\s*-->', $data)) {
                    $data = preg_replace(
                         '/(\s*<!--\s*assets-' . $group . '+\s*-->\s*)/i',
                         "\n" . '<?php echo \helpers\Assets::instance()->renderGroup(' . $group . '); ?>', 
                         $data, 1);
                }
            }
            return $data;
        });
```

and in my template I have

```html
    <!-- assets-head -->
```

I have checked that the content of the returned $data is correct and new data is written in it but the generated chacehd template does not contain the new replacement.

**Comment by ikkez** [comment]
Do you mean "cached" template or the pre-compiled template? For caching templates you need to have caching enabled, and set a $ttl for the render method, like `\Template::instance()->render('index.html',null,null,3600);`. The afterrender implementation looks good, the output should be in the cached template file. 
Whereas the afterrender content changes are not intended to belong into the pre-compiled template file you'll find i.e. at `/tmp/1rwqkho33sqsg.3hl4k3fck6io0.php`. That's why it's called **after**render.

**Comment by GhaziTriki** [comment]
Yes sorry I meant pre-compiled templates.Then what method should it be used to add a final processing the generated prec-compiled templates? To have something working for what I have written.

**Comment by ikkez** [comment]
No one. Instead of `<!-- assets-head -->` just put the call right into your template:
```
{{ \helpers\Assets::instance()->renderGroup('head'); }}
```

**Comment by GhaziTriki** [comment]
That is what I thought about. Thanks. Great framework, however the minification has to be improved, I had to use https://github.com/matthiasmullie/minify but it is another subject.
