### ISSUE TITLE
"Fatal error: Cannot declare class Cache, because the name is already in use" when trying to use Twig

### ISSUE THREAD

**Issue by adrianocr** [bcosca/fatfree#933]
Ask the title says if you install Twig and try to use it, apparently Twig's cache and F3's cache conflict with each other's class name. Is there a possible solution?

**Comment by ikkez** [comment]
There is no class named `Cache` when I search in https://github.com/twigphp/Twig 
Are you sure that you do not have created another Cache class on your own?

**Comment by adrianocr** [comment]
@ikkez you're right. But the only reference to class Cache in the entire directory I found (used PhpStorm to search the entire project) was in /lib/base.php. 

The error only happens when I require composer's autoload.php file. Doesn’t seem to be a Twig issue. Something with how Composer is loading things. I'm not sure.

**Comment by GhaziTriki** [comment]
I have a similar issue with f3-cortex and it reported here https://github.com/ikkez/f3-cortex/issues/25 I think it is related to the fact that we are using composer.

**Comment by ikkez** [comment]
I think this can be solved with a composer config adjustment. have you checked my composer sample at https://github.com/ikkez/f3-cortex/issues/25#issuecomment-214021694 ?

**Comment by cptstoneee** [comment]
I have similar issue:
"Internal Server Error
Fatal error: Cannot declare class Controller\BrowseSpotify, because the name is already in use"

Honestly, I have no idea where this error comes from / is rooted.
I`m working with the spotify api.

What I did:
have 2 routes:
===============================================
<?php
$f3->route('GET /', 'Controller\IndexController->index');
$f3->route('GET /test', 'Controller\SpotifyController->showBrowseGlobal');
===============================================
I have a file called "IndexController" and a class called 'index'.
which contains some code to access the spotify api, as written in their docu.

I have another file calles "SpotifyController and a class called 'show'
If I put the same code from IndexController in the SpotifyController I get the fatal error.
I`m really clueless.

Both files have included:
namespace Controller;
use \SpotifyWebAPI;
use \Template;

Many thanks for further help, anybody!!

**Comment by xfra35** [comment]
@adrianocr I could not reproduce your issue. Could you share a minimum setup (composer.json and index.php) to reproduce it?

**Comment by cptstoneee** [comment]
@myself, a friend could help out. Had nothing to do with fatfree.
Problem was in my code. I called in my route "SpotifyController" but the class in SpotifyController.php had a different name. It´s more an issue of php convention.
Maybe this is of help....?
