### ISSUE TITLE
Error sending email because SMTP from header is being exploded when it contains a name then an email

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#940]
Hi,
I am setting the `From` value of the email using this commnad

``` php
$this->smtp->set('From', 'Pretty Easy LMS <contact@prettylms.com>');
```

The generated head look like

```
From: <Pretty>, <Easy>, <LMS>, <contact@prettylms.com>
```

And makes the email sending fail.

**Comment by KOTRET** [comment]
_imho_ the format you provided is correct.
@bcosca: no clue what the regex `(?:".+?" )?(?:<.+?>|[^ ,]+)` is for, but it just splits at `[^ ,]` (including space) in this case :grin: its hard to do this via regex, because there are so many variants how an address can look like. Also many mailservers accept an address without the angle brackets...

some parts from RFC5322 - Internet Message Format:
Sections [3.2.5](https://tools.ietf.org/html/rfc5322#section-3.2.5)
```
   word            =   atom / quoted-string
   phrase          =   1*word / obs-phrase
```
Section [3.4](https://tools.ietf.org/html/rfc5322#section-3.4):
```
   address         =   mailbox / group
   mailbox         =   name-addr / addr-spec
   name-addr       =   [display-name] angle-addr
   angle-addr      =   [CFWS] "<" addr-spec ">" [CFWS]
   display-name    =   phrase
   mailbox-list    =   (mailbox *("," mailbox))
   address-list    =   (address *("," address))
```
Section [3.2.3](https://tools.ietf.org/html/rfc5322#section-3.2.3) shows the requirements for quoting: only if the string contains
```
"(" / ")" /        ; Special characters that do
"<" / ">" /        ;  not appear in atext
"[" / "]" /
":" / ";" /
"@" / "\" /
"," / "." /
```

**Comment by ptdev** [comment]
Have you tried:

- Using the latest version from https://github.com/bcosca/fatfree-core

or/and

- Adding quotes on the email name like so:
```
$this->smtp->set('From', '"Pretty Easy LMS" <contact@prettylms.com>');
```

It should work as I've recently also had some issues with the smtp class but everything has since been corrected and I'm now sending emails correctly.

**Comment by GhaziTriki** [comment]
I was testing with the latest version of fatfree-core, however the second solution worked fine.

**Comment by ta6rma** [comment]
Still happening with 3.6

**Comment by GhaziTriki** [comment]
@ta6rma it is not fixed yet

**Comment by royhg** [comment]
Does any one have ever send with multiple targets to: SMTP?

It should set $mailer->set('To'," 'name1' <mail1@domain.com>, 'name2' <mail2@domain.com> ")?
or using array?
Does uppercase lowercase char for 'To' influenced here?

regards,

**Comment by KOTRET** [comment]
@royhg please use the google groups for questions, not the bugtracker
