### ISSUE TITLE
Using default behaviour of xcache_unset_by_prefix not possible

### ISSUE THREAD

**Issue by GhaziTriki** [bcosca/fatfree#953]
Hello,

I have checked the following lines https://github.com/bcosca/fatfree-core/blob/2e72dcc9e156421191bac974fbee0f24c646abcc/base.php#L2411-L2413 and it seems to be impossible to use the native `xcache_unset_by_prefix`. If would like to remove all entries starting with `group.invitation.count`.How should I proceed? I my case it will reset all the cache if I use XCache.

Is it possible to imporve that and make it use the `$suffix` as a prefix?

**Comment by GhaziTriki** [comment]
Any update for this issue?

**Comment by GhaziTriki** [comment]
@bcosca did you take a look at it?

**Comment by bcosca** [comment]
I'm unsure what you mean by using "the $suffix as prefix".

**Comment by KOTRET** [comment]
@GhaziTriki: the answer heavily depends on how the values are set - via framework (so that they contain the hash too) or manually? If through f3: the key contains the hash as prefix too, so atm there is no chance to do that.
If manually, you would need to set the `Cache->$prefix` to `group.invitation.count`, which is not possible - call the function manually then.

@bcosca: to achieve at least a reset with hash + custom prefix, I guess this can do it: `xcache_unset_by_prefix($this->prefix.'.'.$suffix.'.');`. The var-name "suffix" is not completely consistent here.

**Comment by GhaziTriki** [comment]
What I mean is that `reset` is deleting all the cache key for xcache while it should use the `$suffix` value to delete all key starting by `$suffix`. @KOTRET Your solution is good, the $suffix variable is consistent, but its name isn't.

**Comment by xfra35** [comment]
The `$suffix` argument is properly named. It has never been meant to be a prefix.

It is here to give the ability to reset cached SQL queries that have been tagged using the `[$ttl,$tag]` syntax:

```php
$db->exec($sql,NULL,[86400,'foo']);
$cache->reset('.foo');
```

What you're asking for is a new feature, which would allow to reset cache entries by prefix.

It concerns all cache engines, not only XCache, so I'll close that issue. You can open a dedicated issue for the "reset by prefix" feature request if you still need it.

BTW, there was a bug in the code that prevented the "reset by suffix" feature to work with XCache. It has been fixed in https://github.com/bcosca/fatfree-core/commit/8d10edc839cb8f47e1bf8c9351595b438c22b4d0 and https://github.com/bcosca/fatfree-core/commit/0436a4e312a6de684041a94e4eef10e3f2295b1, although it requires the `xcache.admin.enable_auth` to be disabled.
