### ISSUE TITLE
Manage emojis in mysql

### ISSUE THREAD

**Issue by severo** [bcosca/fatfree#976]
Hi, I proposed a quick fix in selfoss, that uses f3, to be able to manage emojis with mysql:

https://github.com/SSilence/selfoss/pull/813

The fix is to replace `utf8` character set by `utf8mb4`, and the `utf8_general_ci` collation by `utf8mb4_general_ci`.

I don't know anything about f3, that's why I prefer not to propose a pull request. Please ask if you need more details.

**Comment by jtojnar** [comment]
## Allow to specify database encoding separately

Because MySQL is a crappy database, the thing they call `utf8` is not actually UTF-8. For full UTF-8 support we need to set the encoding to `utf8mb4`. [Currently](https://github.com/bcosca/fatfree/blob/943df693fa3b183f7fec6fb09f9c9f89413228e6/lib/db/sql.php#L465), the database encoding can only be set using application’s `ENCODING` property, which of course should not be `utf8mb4`. We therefore need a separate property for setting database encoding.

**Comment by xfra35** [comment]
You don't have to tweak the framework. Just pass the desired option to the constructor:
```php
$db = new \DB\SQL(
  'mysql:host=localhost;port=3306;dbname=mysqldb',
  'username',
  'password', 
  [\PDO::MYSQL_ATTR_INIT_COMMAND=>'SET NAMES utf8mb4;']
);
```

**Comment by xfra35** [comment]
In Selfoss, that seems to happen here https://github.com/SSilence/selfoss/blob/9c410c71e67304b3860d52eb179b74d7d6289ca2/daos/mysql/Database.php#L32
