### ISSUE TITLE
Unable to clear cookies containing a hyphen

### ISSUE THREAD

**Issue by misterunknown** [bcosca/fatfree#990]
Hi. In my current application I set several cookies for temporary caching, which contain hyphens in their names. When I try to clear such a cookie (`$f3->clear('COOKIE.name-with-hyphen);`) I get the following error from PHP:

```
Fatal error: syntax error, unexpected '-', expecting ',' or ')'
500
Internal Server Error
Fatal error: syntax error, unexpected '-', expecting ',' or ')'

[fatfree/padlock/lib/base.php(434) : eval()'d code:1]
```

I happily worked around this issue by replacing the hyphens with underscores, but considered this a bug, so I guess you should know about it.

This said, I also want to thank you very much for your work. This is an amazing framework, I really love it!

**Comment by bcosca** [comment]
We are fully aware that the RFC specs allow more than just alphanumeric characters as cookie names. However, the framework's consistency of usage becomes intolerable if we have names with special characters `!#$%&'*+-.^_`|~` when used like `$f3->get('COOKIE.abc&xyz')` or `$f3->get('COOKIE.abc+xyz')`. It gets works when used in templates: `@COOKIE.abc+xyz`.

Sorry to break your balls, but the framework's naming restriction is is clearly intentional. Won't fix.
